# This file contains values from Cookiecutter

default_context:
  project_name: "conplex-dti"
  project_description: "Adapting protein language models and contrastive learning for DTI prediction."
  organization: "samsledje"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "samsledje"
  email: "samsl@mit.edu"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
